# manifests/httpd/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-httpd
  namespace: argocd
  labels:
    app: simple-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-httpd
  template:
    metadata:
      labels:
        app: simple-httpd
    spec:
      # Volume akan diisi oleh ConfigMap yang dihasilkan oleh Kustomize
      volumes:
        - name: httpd-html-volume
          configMap:
            name: httpd-index-html # NAMA INI AKAN DIUBAH OLEH KUSTOMIZE
      containers:
        - name: httpd
          image: httpd:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: httpd-html-volume
              mountPath: /usr/local/apache2/htdocs/
