# manifests/httpd/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-httpd-svc
  namespace: web-argocd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30091
  selector:
    app: simple-httpd
