apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Referensi ke folder base NGINX dan HTTPD
bases:
  - nginx
  - httpd

configMapGenerator:
  - name: nginx-index
    files:
      - nginx/index.html
  - name: httpd-index-html
    files:
      - httpd/index.html
